// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const listRoutes = `-- name: ListRoutes :many
SELECT id, subdomain, target_url
FROM env_master
ORDER BY id
`

func (q *Queries) ListRoutes(ctx context.Context) ([]EnvMaster, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvMaster
	for rows.Next() {
		var i EnvMaster
		if err := rows.Scan(&i.ID, &i.Subdomain, &i.TargetUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
